import { Router } from 'express';
import { pool } from '../db/pool.js';
import { requirePermission } from '../auth/authorization.js';
import { isIsoDate, isPositiveInteger } from '../validation.js';
import { allocateStatutoryContributions, calculateStatutoryContributions } from '../payroll/compliance.js';
import { calculatePhilippineWithholding } from '../payroll/tax.js';

export const payoutRouter=Router();
const dayNames=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'];
const round=value=>Math.round(Number(value)*100)/100;
const minutes=value=>{const[hour,minute]=String(value).slice(0,5).split(':').map(Number);return hour*60+minute;};

payoutRouter.post('/employees/:employeeId/payout-preview',...requirePermission('payout_view','view'),async(request,response,next)=>{
  try{
    const employeeId=String(request.params.employeeId),body=request.body||{},periodStart=String(body.periodStart||''),periodEnd=String(body.periodEnd||''),payDate=String(body.payDate||'');
    if(!isPositiveInteger(employeeId)||!isIsoDate(periodStart)||!isIsoDate(periodEnd)||!isIsoDate(payDate)||periodStart>periodEnd||(new Date(`${periodEnd}T00:00:00Z`)-new Date(`${periodStart}T00:00:00Z`))/86400000>31)return response.status(400).json({error:'Enter a valid employee and pay period of up to 31 days.'});
    const profileResult=await pool.query(`SELECT employee.employee_number AS "employeeNumber",employee.first_name AS "firstName",employee.last_name AS "lastName",profile.pay_basis AS "payBasis",profile.pay_frequency AS "payFrequency",profile.base_rate AS "baseRate",profile.standard_hours_per_day AS "standardHoursPerDay",profile.tax_status AS "taxStatus",profile.is_minimum_wage_earner AS "isMinimumWageEarner",profile.auto_calculate_contributions AS "autoCalculateContributions",profile.contribution_deduction_schedule AS "contributionDeductionSchedule",profile.sss_employee_share AS "sssEmployeeShare",profile.philhealth_employee_share AS "philhealthEmployeeShare",profile.pagibig_employee_share AS "pagibigEmployeeShare",profile.union_dues AS "unionDues",COALESCE(TO_CHAR(shift.start_time,'HH24:MI'),'08:00') AS "startTime",COALESCE(TO_CHAR(shift.end_time,'HH24:MI'),'17:00') AS "endTime",COALESCE(shift.work_days,ARRAY['monday','tuesday','wednesday','thursday','friday']::text[]) AS "workDays" FROM employee_profiles employee JOIN employee_payroll_profiles profile ON profile.employee_id=employee.id LEFT JOIN employee_shift_assignments shift ON shift.employee_id=employee.id WHERE employee.id=$1`,[employeeId]);
    if(!profileResult.rowCount)return response.status(404).json({error:'Employee payroll setup was not found.'});
    const profile=profileResult.rows[0];
    const [entriesResult,componentsResult]=await Promise.all([
      pool.query(`SELECT DISTINCT attendance.entry->>'timestamp' AS timestamp,TO_CHAR((attendance.entry->>'timestamp')::timestamptz AT TIME ZONE 'Asia/Manila','YYYY-MM-DD') AS date,TO_CHAR((attendance.entry->>'timestamp')::timestamptz AT TIME ZONE 'Asia/Manila','HH24:MI') AS "localTime" FROM scheduler_backups backup CROSS JOIN LATERAL jsonb_array_elements(backup.attendance) attendance(entry) WHERE CASE WHEN attendance.entry->>'userId'~'^[0-9]+$' AND $1~'^[0-9]+$' THEN (attendance.entry->>'userId')::numeric=$1::numeric ELSE attendance.entry->>'userId'=$1 END AND ((attendance.entry->>'timestamp')::timestamptz AT TIME ZONE 'Asia/Manila')::date BETWEEN $2::date AND $3::date ORDER BY timestamp`,[profile.employeeNumber,periodStart,periodEnd]),
      pool.query(`SELECT component_type AS type,name,amount,calculation,is_taxable AS "isTaxable" FROM employee_payroll_components WHERE employee_id=$1 AND is_active=TRUE ORDER BY type,name`,[employeeId])
    ]);
    const entriesByDate=new Map();for(const entry of entriesResult.rows){const list=entriesByDate.get(entry.date)||[];if(!list.length||new Date(entry.timestamp)-new Date(list[list.length-1].timestamp)>300000)list.push(entry);entriesByDate.set(entry.date,list);}
    const scheduledDates=[];for(let date=new Date(`${periodStart}T00:00:00Z`);date<=new Date(`${periodEnd}T00:00:00Z`);date.setUTCDate(date.getUTCDate()+1))if(profile.workDays.includes(dayNames[date.getUTCDay()]))scheduledDates.push(date.toISOString().slice(0,10));
    let periodBase=Number(profile.baseRate);if(profile.payBasis==='monthly'&&profile.payFrequency==='semi_monthly')periodBase/=2;if(profile.payBasis==='monthly'&&profile.payFrequency==='weekly')periodBase=periodBase*12/52;if(profile.payBasis==='monthly'&&profile.payFrequency==='biweekly')periodBase=periodBase*12/26;if(profile.payBasis==='daily')periodBase=Number(profile.baseRate)*scheduledDates.length;if(profile.payBasis==='hourly')periodBase=Number(profile.baseRate)*Number(profile.standardHoursPerDay)*scheduledDates.length;
    const minuteRate=profile.payBasis==='hourly'?Number(profile.baseRate)/60:profile.payBasis==='daily'?Number(profile.baseRate)/Number(profile.standardHoursPerDay)/60:scheduledDates.length?periodBase/scheduledDates.length/Number(profile.standardHoursPerDay)/60:0;
    const attendanceDays=scheduledDates.map(date=>{const punches=entriesByDate.get(date)||[];let late=0,breakExcess=0,undertime=0,absent=false;if(!punches.length)absent=true;else{late=Math.max(0,minutes(punches[0].localTime)-minutes(profile.startTime));if(punches.length>=3)breakExcess=Math.max(0,minutes(punches[2].localTime)-minutes(punches[1].localTime)-60);if(punches.length>=2)undertime=Math.max(0,minutes(profile.endTime)-minutes(punches[punches.length-1].localTime));}const penaltyMinutes=Math.min(Number(profile.standardHoursPerDay)*60,absent?Number(profile.standardHoursPerDay)*60:late+breakExcess+undertime);return{date,punches:punches.map(item=>item.timestamp),absent,lateMinutes:late,breakExcessMinutes:breakExcess,undertimeMinutes:undertime,penaltyMinutes,deduction:round(penaltyMinutes*minuteRate)};});
    const attendanceDeduction=round(attendanceDays.reduce((sum,day)=>sum+day.deduction,0)),adjustedBase=Math.max(0,round(periodBase-attendanceDeduction));
    const componentValue=item=>round(item.calculation==='percentage'?adjustedBase*Number(item.amount)/100:Number(item.amount));
    const earnings=componentsResult.rows.filter(item=>item.type==='earning').map(item=>({...item,value:componentValue(item)})),deductions=componentsResult.rows.filter(item=>item.type==='deduction').map(item=>({...item,value:componentValue(item)}));
    const taxableEarnings=round(earnings.filter(item=>item.isTaxable).reduce((sum,item)=>sum+item.value,0)),nonTaxableEarnings=round(earnings.filter(item=>!item.isTaxable).reduce((sum,item)=>sum+item.value,0)),recurringDeductions=round(deductions.reduce((sum,item)=>sum+item.value,0));
    const monthly=calculateStatutoryContributions(profile.baseRate),automatic=allocateStatutoryContributions(monthly,{frequency:profile.payFrequency,payDate,schedule:profile.contributionDeductionSchedule});
    const contributions=profile.autoCalculateContributions&&profile.payBasis==='monthly'?automatic:{sssEmployee:Number(profile.sssEmployeeShare),philhealthEmployee:Number(profile.philhealthEmployeeShare),pagibigEmployee:Number(profile.pagibigEmployeeShare),totalEmployee:round(Number(profile.sssEmployeeShare)+Number(profile.philhealthEmployeeShare)+Number(profile.pagibigEmployeeShare)),allocation:{frequency:profile.payFrequency,schedule:'manual',payDate}};
    const tableFrequency=profile.payFrequency==='biweekly'?'weekly':profile.payFrequency,taxConfig=await pool.query(`SELECT id,name FROM tax_configurations WHERE pay_frequency=$1 AND is_active=TRUE AND effective_from<=$2::date AND(effective_to IS NULL OR effective_to>=$2::date) ORDER BY effective_from DESC LIMIT 2`,[tableFrequency,payDate]);
    if(taxConfig.rowCount!==1)return response.status(409).json({error:taxConfig.rowCount?'Multiple active tax configurations match this payout.':'No active tax configuration matches this payout.'});
    const brackets=(await pool.query(`SELECT lower_bound AS "lowerBound",upper_bound AS "upperBound",base_tax AS "baseTax",rate_percent AS "ratePercent" FROM tax_brackets WHERE configuration_id=$1 ORDER BY lower_bound`,[taxConfig.rows[0].id])).rows;
    const taxResult=calculatePhilippineWithholding({regularCompensation:adjustedBase,supplementaryCompensation:taxableEarnings,mandatoryContributions:contributions.totalEmployee+Number(profile.unionDues),taxStatus:profile.taxStatus,isMinimumWageEarner:profile.isMinimumWageEarner,frequency:profile.payFrequency,brackets});
    const grossPay=round(adjustedBase+taxableEarnings+nonTaxableEarnings),totalDeductions=round(attendanceDeduction+contributions.totalEmployee+Number(profile.unionDues)+recurringDeductions+taxResult.tax),netPay=round(grossPay-contributions.totalEmployee-Number(profile.unionDues)-recurringDeductions-taxResult.tax);
    return response.json({employee:{employeeNumber:profile.employeeNumber,name:`${profile.firstName} ${profile.lastName}`},period:{periodStart,periodEnd,payDate,payFrequency:profile.payFrequency},salary:{configuredBase:Number(profile.baseRate),periodBase:round(periodBase),adjustedBase,attendanceDeduction},attendance:{scheduledDays:scheduledDates.length,days:attendanceDays,totalPenaltyMinutes:attendanceDays.reduce((sum,day)=>sum+day.penaltyMinutes,0)},earnings,deductions,contributions,unionDues:Number(profile.unionDues),tax:{amount:taxResult.tax,taxableIncome:taxResult.taxableIncome,configuration:taxConfig.rows[0]},grossPay,totalDeductions,netPay});
  }catch(error){return next(error);}
});
