import crypto from 'node:crypto';
import { Router } from 'express';
import { hasPermission, requireAuth, requirePermission as requireModulePermission } from '../auth/authorization.js';
import { config } from '../config.js';
import { pool } from '../db/pool.js';
import { removePreviouslySynced, uniqueAttendanceRecords } from '../sync/deduplicate.js';
import { isPositiveInteger } from '../validation.js';
export const schedulerRouter = Router();
schedulerRouter.get('/device-users/devices', ...requireModulePermission('device_users','view'), async (_request,response,next) => {
  try {
    const result=await pool.query(`SELECT id,name,host(ip_address) AS ip,port,
      CASE WHEN status='unknown' AND updated_at < NOW()-INTERVAL '45 seconds' THEN 'offline'
           WHEN last_checked_at IS NULL OR last_checked_at < NOW()-INTERVAL '60 seconds' THEN 'unknown'
           ELSE status END AS status,
      last_checked_at AS "lastCheckedAt"
      FROM scheduler_devices WHERE agent_id=$1 ORDER BY name`,[config.syncAgentId]);
    return response.json({devices:result.rows});
  } catch(error){return next(error);}
});
function requirePermission(moduleKey, operation) {
  if (moduleKey !== 'scheduler') return requireModulePermission(moduleKey, operation);
  return [requireAuth, (request, response, next) => {
    const isDeviceUsersRoute = /^\/devices\/[^/]+\/users(?:\/|$)/.test(request.path);
    const allowedKeys = [isDeviceUsersRoute ? 'device_users' : 'scheduler'];
    const allowed = allowedKeys.some((key) => hasPermission(request.user, key, operation));
    if (!allowed) return response.status(403).json({ error: `You do not have permission to ${operation} this scheduler resource.` });
    return next();
  }];
}
const ipv4Pattern = /^(25[0-5]|2[0-4]\d|1?\d?\d)(\.(25[0-5]|2[0-4]\d|1?\d?\d)){3}$/;
schedulerRouter.use('/status', (_request, response, next) => {
  response.set('Cache-Control', 'no-store, no-cache, must-revalidate');
  next();
});

function requireAgent(request, response, next) {
  const agentId = String(request.get('x-agent-id') || '').trim();
  const supplied = Buffer.from(String(request.get('authorization') || '').replace(/^Bearer\s+/i, ''));
  const expected = Buffer.from(config.syncAgentSecret);
  if (!agentId || !expected.length || supplied.length !== expected.length || !crypto.timingSafeEqual(supplied, expected)) return response.status(401).json({ error: 'Invalid agent credentials.' });
  request.agentId = agentId; return next();
}
schedulerRouter.post('/agent/heartbeat', requireAgent, async (request, response, next) => { try { await pool.query(`INSERT INTO scheduler_agents (agent_id,last_seen_at,metadata) VALUES ($1,NOW(),$2) ON CONFLICT (agent_id) DO UPDATE SET last_seen_at=NOW(),metadata=EXCLUDED.metadata`, [request.agentId, request.body || {}]); await pool.query(`INSERT INTO scheduler_sync_jobs (agent_id,device_id) SELECT d.agent_id,d.id FROM scheduler_devices d JOIN scheduler_sync_configurations c ON c.agent_id=d.agent_id AND c.enabled WHERE d.agent_id=$1 AND d.status='online' AND d.last_checked_at >= NOW()-INTERVAL '60 seconds' AND NOT EXISTS (SELECT 1 FROM scheduler_sync_jobs active WHERE active.device_id=d.id AND active.status IN ('pending','running')) AND NOT EXISTS (SELECT 1 FROM scheduler_sync_jobs recent WHERE recent.device_id=d.id AND recent.requested_at > NOW()-(c.interval_minutes*INTERVAL '1 minute')) ON CONFLICT (device_id) WHERE status IN ('pending','running') AND device_id IS NOT NULL DO NOTHING`,[request.agentId]); return response.status(204).end(); } catch (error) { return next(error); } });
schedulerRouter.get('/agent/devices', requireAgent, async (request, response, next) => { try { const result=await pool.query(`SELECT id,name,host(ip_address) AS ip,port FROM scheduler_devices WHERE agent_id=$1 ORDER BY name`,[request.agentId]); return response.json({devices:result.rows}); } catch(error){return next(error);} });
schedulerRouter.post('/agent/devices/:id/status', requireAgent, async (request, response, next) => { try { const status=request.body?.online?'online':'offline'; const message=String(request.body?.error||'').slice(0,500); await pool.query(`UPDATE scheduler_devices SET status=$1,last_checked_at=NOW(),last_error=$2,updated_at=NOW() WHERE id=$3 AND agent_id=$4`,[status,message,request.params.id,request.agentId]); return response.status(204).end(); } catch(error){return next(error);} });
schedulerRouter.get('/agent/user-pushes/next', requireAgent, async (request,response,next) => { try { const result=await pool.query(`WITH claimed AS (UPDATE scheduler_device_user_pushes SET status='running',started_at=NOW(),error='' WHERE id=(SELECT push.id FROM scheduler_device_user_pushes push JOIN scheduler_devices device ON device.id=push.device_id WHERE push.agent_id=$1 AND push.status='pending' AND device.status='online' ORDER BY push.requested_at LIMIT 1 FOR UPDATE OF push SKIP LOCKED) RETURNING id,device_id,employee_id) SELECT claimed.id,employee.employee_number AS "employeeId",CONCAT_WS(' ',employee.first_name,employee.last_name) AS "employeeName",device.name,host(device.ip_address) AS ip,device.port FROM claimed JOIN employee_profiles employee ON employee.id=claimed.employee_id JOIN scheduler_devices device ON device.id=claimed.device_id`,[request.agentId]); return response.json({push:result.rows[0]||null}); } catch(error){return next(error);} });
schedulerRouter.post('/agent/user-pushes/:id/complete', requireAgent, async (request,response,next) => { try { const result=await pool.query(`UPDATE scheduler_device_user_pushes SET status='completed',completed_at=NOW(),error='' WHERE id=$1 AND agent_id=$2 AND status='running' RETURNING id`,[request.params.id,request.agentId]); if(!result.rowCount)return response.status(409).json({error:'The device user push is not active.'}); return response.status(204).end(); } catch(error){return next(error);} });
schedulerRouter.post('/agent/user-pushes/:id/fail', requireAgent, async (request,response,next) => { try { const message=String(request.body?.error||'Unable to push the user to the device.').slice(0,1000); await pool.query(`UPDATE scheduler_device_user_pushes SET status='failed',completed_at=NOW(),error=$1 WHERE id=$2 AND agent_id=$3 AND status='running'`,[message,request.params.id,request.agentId]); return response.status(204).end(); } catch(error){return next(error);} });
schedulerRouter.get('/agent/user-checks/next', requireAgent, async (request,response,next) => { try { const result=await pool.query(`WITH stale AS (UPDATE scheduler_device_user_checks SET status='pending',started_at=NULL,error='Previous device user check timed out and was retried.' WHERE agent_id=$1 AND status='running' AND started_at<NOW()-INTERVAL '1 minute'), claimed AS (UPDATE scheduler_device_user_checks SET status='running',started_at=NOW(),error='' WHERE id=(SELECT check_job.id FROM scheduler_device_user_checks check_job JOIN scheduler_devices device ON device.id=check_job.device_id WHERE check_job.agent_id=$1 AND check_job.status='pending' AND device.status='online' ORDER BY check_job.requested_at LIMIT 1 FOR UPDATE OF check_job SKIP LOCKED) RETURNING id,device_id) SELECT claimed.id,device.name,host(device.ip_address) AS ip,device.port FROM claimed JOIN scheduler_devices device ON device.id=claimed.device_id`,[request.agentId]); return response.json({check:result.rows[0]||null}); } catch(error){return next(error);} });
schedulerRouter.post('/agent/user-checks/:id/complete', requireAgent, async (request,response,next) => {
  const deviceUsers=request.body?.users; if(!Array.isArray(deviceUsers)||deviceUsers.length>10000)return response.status(400).json({error:'The device returned an invalid user list.'});
  const client=await pool.connect(); try { await client.query('BEGIN'); const check=await client.query(`SELECT id,device_id FROM scheduler_device_user_checks WHERE id=$1 AND agent_id=$2 AND status='running' FOR UPDATE`,[request.params.id,request.agentId]); if(!check.rowCount){await client.query('ROLLBACK');return response.status(409).json({error:'The device user check is not active.'});} const deviceId=check.rows[0].device_id; const employees=await client.query(`SELECT id,employee_number FROM employee_profiles WHERE employment_status='active' AND CASE WHEN employee_number ~ '^\\d{1,9}$' THEN employee_number::numeric BETWEEN 1 AND 65535 ELSE FALSE END`); const present=new Set(deviceUsers.filter((user)=>Number(user.uid)>=1&&Number(user.uid)<=65535&&Number(user.role)===0&&Number(user.employeeId)===Number(user.uid)).map((user)=>String(user.employeeId))); let queued=0; for(const employee of employees.rows){const isPresent=present.has(employee.employee_number);if(!isPresent)queued+=1;await client.query(`INSERT INTO scheduler_device_user_pushes (agent_id,device_id,employee_id,status,completed_at,error) VALUES ($1,$2,$3,$4,CASE WHEN $4='completed' THEN NOW() ELSE NULL END,'') ON CONFLICT (device_id,employee_id) DO UPDATE SET status=CASE WHEN scheduler_device_user_pushes.status='running' THEN 'running' ELSE EXCLUDED.status END,requested_at=CASE WHEN EXCLUDED.status='pending' THEN NOW() ELSE scheduler_device_user_pushes.requested_at END,started_at=CASE WHEN EXCLUDED.status='pending' AND scheduler_device_user_pushes.status<>'running' THEN NULL ELSE scheduler_device_user_pushes.started_at END,completed_at=CASE WHEN EXCLUDED.status='completed' THEN NOW() WHEN scheduler_device_user_pushes.status='running' THEN scheduler_device_user_pushes.completed_at ELSE NULL END,error=CASE WHEN scheduler_device_user_pushes.status='running' THEN scheduler_device_user_pushes.error ELSE '' END`,[request.agentId,deviceId,employee.id,isPresent?'completed':'pending']);} await client.query(`UPDATE scheduler_device_user_checks SET status='completed',completed_at=NOW(),users_found=$1,users_queued=$2,error='' WHERE id=$3`,[deviceUsers.length,queued,request.params.id]); await client.query('COMMIT'); return response.json({usersFound:deviceUsers.length,usersQueued:queued}); } catch(error){await client.query('ROLLBACK');return next(error);} finally{client.release();}
});
schedulerRouter.post('/agent/user-checks/:id/fail', requireAgent, async (request,response,next) => { try { const message=String(request.body?.error||'Unable to check users on the device.').slice(0,1000); await pool.query(`UPDATE scheduler_device_user_checks SET status='failed',completed_at=NOW(),error=$1 WHERE id=$2 AND agent_id=$3 AND status='running'`,[message,request.params.id,request.agentId]); return response.status(204).end(); } catch(error){return next(error);} });
schedulerRouter.get('/agent/jobs/next', requireAgent, async (request, response, next) => { try { const result = await pool.query(`WITH stale AS (UPDATE scheduler_sync_jobs SET status='pending',started_at=NULL,error='Previous synchronization timed out and was retried.' WHERE agent_id=$1 AND status='running' AND started_at<NOW()-INTERVAL '2 minutes'), claimed AS (UPDATE scheduler_sync_jobs SET status='running',started_at=NOW() WHERE id=(SELECT id FROM scheduler_sync_jobs WHERE agent_id=$1 AND status='pending' AND device_id IS NOT NULL ORDER BY requested_at LIMIT 1 FOR UPDATE SKIP LOCKED) RETURNING id,device_id) SELECT claimed.id,d.id AS "deviceId",d.name,d.ip,d.port FROM claimed JOIN (SELECT id,name,host(ip_address) AS ip,port FROM scheduler_devices) d ON d.id=claimed.device_id`, [request.agentId]); return response.json({ job: result.rows[0] || null }); } catch (error) { return next(error); } });
schedulerRouter.post('/agent/backups', requireAgent, async (request, response, next) => {
  const { jobId, backup } = request.body || {}; if (!jobId) return response.status(400).json({ error: 'A synchronization job ID is required.' }); if (!backup?.createdAt || !backup.device || !Array.isArray(backup.users) || !Array.isArray(backup.attendance)) return response.status(400).json({ error: 'The device returned an invalid backup payload.' });
  const client = await pool.connect(); try { await client.query('BEGIN'); const job=await client.query(`SELECT j.id,j.device_id FROM scheduler_sync_jobs j JOIN scheduler_devices d ON d.id=j.device_id WHERE j.id=$1 AND j.agent_id=$2 AND j.status='running' FOR UPDATE OF d`,[jobId,request.agentId]); if(!job.rowCount||!job.rows[0].device_id){await client.query('ROLLBACK');return response.status(409).json({error:'The synchronization job is not active for a registered device.'});} const deviceId=job.rows[0].device_id; const previous=await client.query(`SELECT users,attendance FROM scheduler_backups WHERE device_id=$1`,[deviceId]); const newBackup=removePreviouslySynced(backup,previous.rows); const saved = await client.query(`INSERT INTO scheduler_backups (agent_id,job_id,device_id,captured_at,device,users,attendance) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id`, [request.agentId, jobId, deviceId, newBackup.createdAt, newBackup.device, JSON.stringify(newBackup.users), JSON.stringify(newBackup.attendance)]); await client.query(`UPDATE scheduler_sync_jobs SET status='completed',completed_at=NOW(),error='' WHERE id=$1`, [jobId]); await client.query(`INSERT INTO scheduler_agents (agent_id,last_seen_at,last_sync_at,last_error) VALUES ($1,NOW(),NOW(),'') ON CONFLICT (agent_id) DO UPDATE SET last_seen_at=NOW(),last_sync_at=NOW(),last_error=''`, [request.agentId]); await client.query('COMMIT'); return response.status(201).json({ backupId: saved.rows[0].id, users: newBackup.users.length, attendance: newBackup.attendance.length }); } catch (error) { await client.query('ROLLBACK'); return next(error); } finally { client.release(); }
});
schedulerRouter.post('/agent/jobs/:id/fail', requireAgent, async (request, response, next) => { try { const message = String(request.body?.error || 'Device synchronization failed.').slice(0,1000); await pool.query(`UPDATE scheduler_sync_jobs SET status='failed',completed_at=NOW(),error=$1 WHERE id=$2 AND agent_id=$3`, [message, request.params.id, request.agentId]); await pool.query(`UPDATE scheduler_agents SET last_seen_at=NOW(),last_error=$1 WHERE agent_id=$2`, [message, request.agentId]); return response.status(204).end(); } catch (error) { return next(error); } });
schedulerRouter.get('/status', ...requirePermission('scheduler','view'), async (_request,response,next) => { try { const [agent,jobs,backups,devices,syncConfiguration]=await Promise.all([pool.query(`SELECT agent_id AS "agentId",last_seen_at AS "lastSeenAt",last_sync_at AS "lastSyncAt",last_error AS "lastError",metadata FROM scheduler_agents WHERE agent_id=$1`,[config.syncAgentId]),pool.query(`SELECT id,device_id AS "deviceId",status,requested_at AS "requestedAt",started_at AS "startedAt",completed_at AS "completedAt",error FROM scheduler_sync_jobs WHERE agent_id=$1 ORDER BY requested_at DESC LIMIT 25`,[config.syncAgentId]),pool.query(`SELECT id,device_id AS "deviceId",captured_at AS "capturedAt",jsonb_array_length(users) AS users,attendance,device FROM scheduler_backups WHERE agent_id=$1 ORDER BY uploaded_at DESC LIMIT 25`,[config.syncAgentId]),pool.query(`SELECT id,name,host(ip_address) AS ip,port,CASE WHEN status='unknown' AND updated_at < NOW()-INTERVAL '45 seconds' THEN 'offline' WHEN last_checked_at IS NULL OR last_checked_at < NOW()-INTERVAL '60 seconds' THEN 'unknown' ELSE status END AS status,last_checked_at AS "lastCheckedAt",CASE WHEN status='unknown' AND updated_at < NOW()-INTERVAL '45 seconds' THEN 'Connectivity refresh timed out after 45 seconds.' WHEN last_checked_at IS NULL OR last_checked_at < NOW()-INTERVAL '60 seconds' THEN 'Status is stale. The current agent has not checked this device recently.' ELSE last_error END AS "lastError" FROM scheduler_devices WHERE agent_id=$1 ORDER BY name`,[config.syncAgentId]),pool.query(`SELECT enabled,interval_minutes AS "intervalMinutes",updated_at AS "updatedAt" FROM scheduler_sync_configurations WHERE agent_id=$1`,[config.syncAgentId])]); const backupSummaries=backups.rows.map((backup)=>{const {device,...summary}=backup;const logCount=Number(device?.logCounts)||0;const logCapacity=Number(device?.logCapacity)||0;return {...summary,attendance:uniqueAttendanceRecords(backup.attendance||[]).length,storage:{attendanceRecords:logCount,attendanceCapacity:logCapacity,attendanceAvailable:logCapacity?Math.max(0,logCapacity-logCount):null,utilization:logCapacity?Math.min(100,Math.round((logCount/logCapacity)*100)):null,userRecords:Number(device?.userCounts)||0}};}); return response.json({agent:agent.rows[0]||null,jobs:jobs.rows,backups:backupSummaries,devices:devices.rows,syncConfiguration:syncConfiguration.rows[0]||{enabled:false,intervalMinutes:15}}); } catch(error){return next(error);} });
schedulerRouter.put('/configuration', ...requirePermission('scheduler','update'), async (request,response,next) => { try { const enabled=request.body?.enabled===true; const intervalMinutes=Number(request.body?.intervalMinutes); if(!Number.isInteger(intervalMinutes)||intervalMinutes<1||intervalMinutes>10080)return response.status(400).json({error:'Automatic sync interval must be between 1 and 10,080 minutes.'}); const result=await pool.query(`INSERT INTO scheduler_sync_configurations (agent_id,enabled,interval_minutes,updated_by) VALUES ($1,$2,$3,$4) ON CONFLICT (agent_id) DO UPDATE SET enabled=EXCLUDED.enabled,interval_minutes=EXCLUDED.interval_minutes,updated_by=EXCLUDED.updated_by,updated_at=NOW() RETURNING enabled,interval_minutes AS "intervalMinutes",updated_at AS "updatedAt"`,[config.syncAgentId,enabled,intervalMinutes,request.user.id]); return response.json({syncConfiguration:result.rows[0]}); } catch(error){return next(error);} });
schedulerRouter.get('/devices/:id/users', ...requirePermission('scheduler','view'), async (request,response,next) => { try { if(!isPositiveInteger(request.params.id))return response.status(400).json({error:'A valid device is required.'}); const device=await pool.query(`SELECT id FROM scheduler_devices WHERE id=$1 AND agent_id=$2`,[request.params.id,config.syncAgentId]); if(!device.rowCount)return response.status(404).json({error:'Device not found.'}); const [result,check]=await Promise.all([pool.query(`SELECT employee.id,employee.employee_number AS "employeeId",employee.first_name AS "firstName",employee.last_name AS "lastName",push.status,push.error,CASE WHEN employee.employee_number ~ '^\\d{1,9}$' AND employee.employee_number::numeric BETWEEN 1 AND 65535 THEN TRUE ELSE FALSE END AS eligible FROM employee_profiles employee LEFT JOIN scheduler_device_user_pushes push ON push.employee_id=employee.id AND push.device_id=$1 WHERE employee.employment_status='active' AND (push.id IS NULL OR push.status<>'completed') ORDER BY employee.created_at,employee.id`,[request.params.id]),pool.query(`SELECT status,users_found AS "usersFound",users_queued AS "usersQueued",error,completed_at AS "completedAt" FROM scheduler_device_user_checks WHERE device_id=$1 ORDER BY requested_at DESC LIMIT 1`,[request.params.id])]); return response.json({users:result.rows,check:check.rows[0]||null}); } catch(error){return next(error);} });
schedulerRouter.post('/devices/:id/users/check', ...requirePermission('scheduler','update'), async (request,response,next) => { try { if(!isPositiveInteger(request.params.id))return response.status(400).json({error:'A valid device is required.'}); const device=await pool.query(`SELECT id,status,last_checked_at FROM scheduler_devices WHERE id=$1 AND agent_id=$2`,[request.params.id,config.syncAgentId]); if(!device.rowCount)return response.status(404).json({error:'Device not found.'}); if(device.rows[0].status!=='online')return response.status(409).json({error:'The device must be online before checking its users.'}); const result=await pool.query(`INSERT INTO scheduler_device_user_checks (agent_id,device_id,requested_by) VALUES ($1,$2,$3) ON CONFLICT (device_id) WHERE status IN ('pending','running') DO NOTHING RETURNING id,status`,[config.syncAgentId,request.params.id,request.user.id]); if(!result.rowCount)return response.status(409).json({error:'A device user check is already pending or running.'}); return response.status(202).json({check:result.rows[0]}); } catch(error){return next(error);} });
schedulerRouter.post('/devices/:id/users/push', ...requirePermission('scheduler','update'), async (request,response,next) => { try { if(!isPositiveInteger(request.params.id))return response.status(400).json({error:'A valid device is required.'}); const device=await pool.query(`SELECT id,status FROM scheduler_devices WHERE id=$1 AND agent_id=$2`,[request.params.id,config.syncAgentId]); if(!device.rowCount)return response.status(404).json({error:'Device not found.'}); const result=await pool.query(`INSERT INTO scheduler_device_user_pushes (agent_id,device_id,employee_id,requested_by) SELECT $1,$2,employee.id,$3 FROM employee_profiles employee WHERE employee.employment_status='active' AND CASE WHEN employee.employee_number ~ '^\\d{1,9}$' THEN employee.employee_number::numeric BETWEEN 1 AND 65535 ELSE FALSE END ON CONFLICT (device_id,employee_id) DO UPDATE SET status='pending',requested_by=EXCLUDED.requested_by,requested_at=NOW(),started_at=NULL,completed_at=NULL,error='' WHERE scheduler_device_user_pushes.status='failed' RETURNING id`,[config.syncAgentId,request.params.id,request.user.id]); return response.status(202).json({queued:result.rowCount}); } catch(error){return next(error);} });
schedulerRouter.post('/devices', ...requirePermission('scheduler','create'), async (request,response,next) => { try { const name=String(request.body?.name||'').trim(); const ip=String(request.body?.ip||'').trim(); const port=Number(request.body?.port||4370); if(!name||name.length>120)return response.status(400).json({error:'Device name is required and must be 120 characters or fewer.'}); if(!ipv4Pattern.test(ip))return response.status(400).json({error:'Enter a valid IPv4 address.'}); if(!Number.isInteger(port)||port<1||port>65535)return response.status(400).json({error:'Port must be between 1 and 65535.'}); const result=await pool.query(`INSERT INTO scheduler_devices (agent_id,name,ip_address,port) VALUES ($1,$2,$3,$4) RETURNING id,name,host(ip_address) AS ip,port,status`,[config.syncAgentId,name,ip,port]); return response.status(201).json({device:result.rows[0]}); } catch(error){if(error.code==='23505')return response.status(409).json({error:'That device IP and port are already registered.'});return next(error);} });
schedulerRouter.put('/devices/:id', ...requirePermission('scheduler','update'), async (request,response,next) => { try { const name=String(request.body?.name||'').trim(); const ip=String(request.body?.ip||'').trim(); const port=Number(request.body?.port||4370); if(!name||name.length>120)return response.status(400).json({error:'Device name is required and must be 120 characters or fewer.'}); if(!ipv4Pattern.test(ip))return response.status(400).json({error:'Enter a valid IPv4 address.'}); if(!Number.isInteger(port)||port<1||port>65535)return response.status(400).json({error:'Port must be between 1 and 65535.'}); const result=await pool.query(`UPDATE scheduler_devices SET name=$1,ip_address=$2,port=$3,status='unknown',last_checked_at=NULL,last_error='',updated_at=NOW() WHERE id=$4 AND agent_id=$5 RETURNING id,name,host(ip_address) AS ip,port,status`,[name,ip,port,request.params.id,config.syncAgentId]); if(!result.rowCount)return response.status(404).json({error:'Device not found.'}); return response.json({device:result.rows[0]}); } catch(error){if(error.code==='23505')return response.status(409).json({error:'That device IP and port are already registered.'});return next(error);} });
schedulerRouter.delete('/devices/:id', ...requirePermission('scheduler','delete'), async (request,response,next) => { try { const active=await pool.query(`SELECT id FROM scheduler_sync_jobs WHERE device_id=$1 AND status IN ('pending','running') LIMIT 1`,[request.params.id]); if(active.rowCount)return response.status(409).json({error:'Wait for the active synchronization to finish before removing this device.'}); const result=await pool.query(`DELETE FROM scheduler_devices WHERE id=$1 AND agent_id=$2`,[request.params.id,config.syncAgentId]); if(!result.rowCount)return response.status(404).json({error:'Device not found.'}); return response.status(204).end(); } catch(error){return next(error);} });
schedulerRouter.post('/devices/:id/refresh', ...requirePermission('scheduler','update'), async (request,response,next) => { try { const result=await pool.query(`UPDATE scheduler_devices SET status='unknown',last_checked_at=NULL,last_error='',updated_at=NOW() WHERE id=$1 AND agent_id=$2 RETURNING id`,[request.params.id,config.syncAgentId]); if(!result.rowCount)return response.status(404).json({error:'Device not found.'}); return response.status(202).json({status:'pending'}); } catch(error){return next(error);} });
schedulerRouter.post('/devices/:id/sync', ...requirePermission('scheduler','update'), async (request,response,next) => { try { const device=await pool.query(`SELECT id,status,last_checked_at FROM scheduler_devices WHERE id=$1 AND agent_id=$2`,[request.params.id,config.syncAgentId]); if(!device.rowCount)return response.status(404).json({error:'Device not found.'}); const current=device.rows[0]; if(current.status!=='online'||!current.last_checked_at||Date.now()-new Date(current.last_checked_at).getTime()>10*60*1000)return response.status(409).json({error:'The device must be online with a status check from the last 10 minutes before it can synchronize.'}); const existing=await pool.query(`SELECT id FROM scheduler_sync_jobs WHERE device_id=$1 AND status IN ('pending','running') LIMIT 1`,[request.params.id]); if(existing.rowCount)return response.status(409).json({error:'A synchronization is already pending or running for this device.'}); const result=await pool.query(`INSERT INTO scheduler_sync_jobs (agent_id,device_id,requested_by) VALUES ($1,$2,$3) RETURNING id,device_id AS "deviceId",status,requested_at AS "requestedAt"`,[config.syncAgentId,request.params.id,request.user.id]); return response.status(202).json({job:result.rows[0]}); } catch(error){return next(error);} });
