import crypto from 'node:crypto';
import { Router } from 'express';
import { requirePermission } from '../auth/authorization.js';
import { config } from '../config.js';
import { pool } from '../db/pool.js';
export const schedulerRouter = Router();
const ipv4Pattern = /^(25[0-5]|2[0-4]\d|1?\d?\d)(\.(25[0-5]|2[0-4]\d|1?\d?\d)){3}$/;
schedulerRouter.use('/status', (_request, response, next) => {
  response.set('Cache-Control', 'no-store, no-cache, must-revalidate');
  next();
});

function requireAgent(request, response, next) {
  const agentId = String(request.get('x-agent-id') || '').trim();
  const supplied = Buffer.from(String(request.get('authorization') || '').replace(/^Bearer\s+/i, ''));
  const expected = Buffer.from(config.syncAgentSecret);
  if (!agentId || !expected.length || supplied.length !== expected.length || !crypto.timingSafeEqual(supplied, expected)) return response.status(401).json({ error: 'Invalid agent credentials.' });
  request.agentId = agentId; return next();
}
schedulerRouter.post('/agent/heartbeat', requireAgent, async (request, response, next) => { try { await pool.query(`INSERT INTO scheduler_agents (agent_id,last_seen_at,metadata) VALUES ($1,NOW(),$2) ON CONFLICT (agent_id) DO UPDATE SET last_seen_at=NOW(),metadata=EXCLUDED.metadata`, [request.agentId, request.body || {}]); return response.status(204).end(); } catch (error) { return next(error); } });
schedulerRouter.get('/agent/devices', requireAgent, async (request, response, next) => { try { const result=await pool.query(`SELECT id,name,host(ip_address) AS ip,port FROM scheduler_devices WHERE agent_id=$1 ORDER BY name`,[request.agentId]); return response.json({devices:result.rows}); } catch(error){return next(error);} });
schedulerRouter.post('/agent/devices/:id/status', requireAgent, async (request, response, next) => { try { const status=request.body?.online?'online':'offline'; const message=String(request.body?.error||'').slice(0,500); await pool.query(`UPDATE scheduler_devices SET status=$1,last_checked_at=NOW(),last_error=$2,updated_at=NOW() WHERE id=$3 AND agent_id=$4`,[status,message,request.params.id,request.agentId]); return response.status(204).end(); } catch(error){return next(error);} });
schedulerRouter.get('/agent/jobs/next', requireAgent, async (request, response, next) => { try { const result = await pool.query(`WITH claimed AS (UPDATE scheduler_sync_jobs SET status='running',started_at=NOW() WHERE id=(SELECT id FROM scheduler_sync_jobs WHERE agent_id=$1 AND status='pending' AND device_id IS NOT NULL ORDER BY requested_at LIMIT 1 FOR UPDATE SKIP LOCKED) RETURNING id,device_id) SELECT claimed.id,d.id AS "deviceId",d.name,d.ip,d.port FROM claimed JOIN (SELECT id,name,host(ip_address) AS ip,port FROM scheduler_devices) d ON d.id=claimed.device_id`, [request.agentId]); return response.json({ job: result.rows[0] || null }); } catch (error) { return next(error); } });
schedulerRouter.post('/agent/backups', requireAgent, async (request, response, next) => {
  const { jobId, backup } = request.body || {}; if (!jobId) return response.status(400).json({ error: 'A synchronization job ID is required.' }); if (!backup?.createdAt || !backup.device || !Array.isArray(backup.users) || !Array.isArray(backup.attendance)) return response.status(400).json({ error: 'The device returned an invalid backup payload.' });
  const client = await pool.connect(); try { await client.query('BEGIN'); const job=await client.query(`SELECT id,device_id FROM scheduler_sync_jobs WHERE id=$1 AND agent_id=$2 AND status='running'`,[jobId,request.agentId]); if(!job.rowCount||!job.rows[0].device_id){await client.query('ROLLBACK');return response.status(409).json({error:'The synchronization job is not active for a registered device.'});} const deviceId=job.rows[0].device_id; const saved = await client.query(`INSERT INTO scheduler_backups (agent_id,job_id,device_id,captured_at,device,users,attendance) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id`, [request.agentId, jobId, deviceId, backup.createdAt, backup.device, JSON.stringify(backup.users), JSON.stringify(backup.attendance)]); await client.query(`UPDATE scheduler_sync_jobs SET status='completed',completed_at=NOW(),error='' WHERE id=$1`, [jobId]); await client.query(`INSERT INTO scheduler_agents (agent_id,last_seen_at,last_sync_at,last_error) VALUES ($1,NOW(),NOW(),'') ON CONFLICT (agent_id) DO UPDATE SET last_seen_at=NOW(),last_sync_at=NOW(),last_error=''`, [request.agentId]); await client.query('COMMIT'); return response.status(201).json({ backupId: saved.rows[0].id }); } catch (error) { await client.query('ROLLBACK'); return next(error); } finally { client.release(); }
});
schedulerRouter.post('/agent/jobs/:id/fail', requireAgent, async (request, response, next) => { try { const message = String(request.body?.error || 'Device synchronization failed.').slice(0,1000); await pool.query(`UPDATE scheduler_sync_jobs SET status='failed',completed_at=NOW(),error=$1 WHERE id=$2 AND agent_id=$3`, [message, request.params.id, request.agentId]); await pool.query(`UPDATE scheduler_agents SET last_seen_at=NOW(),last_error=$1 WHERE agent_id=$2`, [message, request.agentId]); return response.status(204).end(); } catch (error) { return next(error); } });
schedulerRouter.get('/status', ...requirePermission('scheduler','view'), async (_request,response,next) => { try { const [agent,jobs,backups,devices]=await Promise.all([pool.query(`SELECT agent_id AS "agentId",last_seen_at AS "lastSeenAt",last_sync_at AS "lastSyncAt",last_error AS "lastError",metadata FROM scheduler_agents WHERE agent_id=$1`,[config.syncAgentId]),pool.query(`SELECT id,device_id AS "deviceId",status,requested_at AS "requestedAt",started_at AS "startedAt",completed_at AS "completedAt",error FROM scheduler_sync_jobs WHERE agent_id=$1 ORDER BY requested_at DESC LIMIT 25`,[config.syncAgentId]),pool.query(`SELECT id,device_id AS "deviceId",captured_at AS "capturedAt",jsonb_array_length(users) AS users,jsonb_array_length(attendance) AS attendance FROM scheduler_backups WHERE agent_id=$1 ORDER BY uploaded_at DESC LIMIT 25`,[config.syncAgentId]),pool.query(`SELECT id,name,host(ip_address) AS ip,port,CASE WHEN status='unknown' AND updated_at < NOW()-INTERVAL '45 seconds' THEN 'offline' WHEN last_checked_at IS NULL OR last_checked_at < NOW()-INTERVAL '60 seconds' THEN 'unknown' ELSE status END AS status,last_checked_at AS "lastCheckedAt",CASE WHEN status='unknown' AND updated_at < NOW()-INTERVAL '45 seconds' THEN 'Connectivity refresh timed out after 45 seconds.' WHEN last_checked_at IS NULL OR last_checked_at < NOW()-INTERVAL '60 seconds' THEN 'Status is stale. The current agent has not checked this device recently.' ELSE last_error END AS "lastError" FROM scheduler_devices WHERE agent_id=$1 ORDER BY name`,[config.syncAgentId])]); return response.json({agent:agent.rows[0]||null,jobs:jobs.rows,backups:backups.rows,devices:devices.rows}); } catch(error){return next(error);} });
schedulerRouter.post('/devices', ...requirePermission('scheduler','create'), async (request,response,next) => { try { const name=String(request.body?.name||'').trim(); const ip=String(request.body?.ip||'').trim(); const port=Number(request.body?.port||4370); if(!name||name.length>120)return response.status(400).json({error:'Device name is required and must be 120 characters or fewer.'}); if(!ipv4Pattern.test(ip))return response.status(400).json({error:'Enter a valid IPv4 address.'}); if(!Number.isInteger(port)||port<1||port>65535)return response.status(400).json({error:'Port must be between 1 and 65535.'}); const result=await pool.query(`INSERT INTO scheduler_devices (agent_id,name,ip_address,port) VALUES ($1,$2,$3,$4) RETURNING id,name,host(ip_address) AS ip,port,status`,[config.syncAgentId,name,ip,port]); return response.status(201).json({device:result.rows[0]}); } catch(error){if(error.code==='23505')return response.status(409).json({error:'That device IP and port are already registered.'});return next(error);} });
schedulerRouter.put('/devices/:id', ...requirePermission('scheduler','update'), async (request,response,next) => { try { const name=String(request.body?.name||'').trim(); const ip=String(request.body?.ip||'').trim(); const port=Number(request.body?.port||4370); if(!name||name.length>120)return response.status(400).json({error:'Device name is required and must be 120 characters or fewer.'}); if(!ipv4Pattern.test(ip))return response.status(400).json({error:'Enter a valid IPv4 address.'}); if(!Number.isInteger(port)||port<1||port>65535)return response.status(400).json({error:'Port must be between 1 and 65535.'}); const result=await pool.query(`UPDATE scheduler_devices SET name=$1,ip_address=$2,port=$3,status='unknown',last_checked_at=NULL,last_error='',updated_at=NOW() WHERE id=$4 AND agent_id=$5 RETURNING id,name,host(ip_address) AS ip,port,status`,[name,ip,port,request.params.id,config.syncAgentId]); if(!result.rowCount)return response.status(404).json({error:'Device not found.'}); return response.json({device:result.rows[0]}); } catch(error){if(error.code==='23505')return response.status(409).json({error:'That device IP and port are already registered.'});return next(error);} });
schedulerRouter.delete('/devices/:id', ...requirePermission('scheduler','delete'), async (request,response,next) => { try { const active=await pool.query(`SELECT id FROM scheduler_sync_jobs WHERE device_id=$1 AND status IN ('pending','running') LIMIT 1`,[request.params.id]); if(active.rowCount)return response.status(409).json({error:'Wait for the active synchronization to finish before removing this device.'}); const result=await pool.query(`DELETE FROM scheduler_devices WHERE id=$1 AND agent_id=$2`,[request.params.id,config.syncAgentId]); if(!result.rowCount)return response.status(404).json({error:'Device not found.'}); return response.status(204).end(); } catch(error){return next(error);} });
schedulerRouter.post('/devices/:id/refresh', ...requirePermission('scheduler','update'), async (request,response,next) => { try { const result=await pool.query(`UPDATE scheduler_devices SET status='unknown',last_checked_at=NULL,last_error='',updated_at=NOW() WHERE id=$1 AND agent_id=$2 RETURNING id`,[request.params.id,config.syncAgentId]); if(!result.rowCount)return response.status(404).json({error:'Device not found.'}); return response.status(202).json({status:'pending'}); } catch(error){return next(error);} });
schedulerRouter.post('/devices/:id/sync', ...requirePermission('scheduler','update'), async (request,response,next) => { try { const device=await pool.query(`SELECT id,status,last_checked_at FROM scheduler_devices WHERE id=$1 AND agent_id=$2`,[request.params.id,config.syncAgentId]); if(!device.rowCount)return response.status(404).json({error:'Device not found.'}); const current=device.rows[0]; if(current.status!=='online'||!current.last_checked_at||Date.now()-new Date(current.last_checked_at).getTime()>10*60*1000)return response.status(409).json({error:'The device must be online with a status check from the last 10 minutes before it can synchronize.'}); const existing=await pool.query(`SELECT id FROM scheduler_sync_jobs WHERE device_id=$1 AND status IN ('pending','running') LIMIT 1`,[request.params.id]); if(existing.rowCount)return response.status(409).json({error:'A synchronization is already pending or running for this device.'}); const result=await pool.query(`INSERT INTO scheduler_sync_jobs (agent_id,device_id,requested_by) VALUES ($1,$2,$3) RETURNING id,device_id AS "deviceId",status,requested_at AS "requestedAt"`,[config.syncAgentId,request.params.id,request.user.id]); return response.status(202).json({job:result.rows[0]}); } catch(error){return next(error);} });
