import { Router } from 'express';
import { pool } from '../db/pool.js';
import { requirePermission } from '../auth/authorization.js';
import { calculatePhilippineWithholding } from '../payroll/tax.js';
export const taxRouter=Router(); const frequencies=new Set(['daily','weekly','semi_monthly','monthly']);
const configurationQuery=`SELECT c.id,c.name,c.effective_from AS "effectiveFrom",c.effective_to AS "effectiveTo",c.pay_frequency AS "payFrequency",c.is_active AS "isActive",COALESCE(jsonb_agg(jsonb_build_object('id',b.id,'lowerBound',b.lower_bound,'upperBound',b.upper_bound,'baseTax',b.base_tax,'ratePercent',b.rate_percent) ORDER BY b.lower_bound) FILTER(WHERE b.id IS NOT NULL),'[]') AS brackets FROM tax_configurations c LEFT JOIN tax_brackets b ON b.configuration_id=c.id GROUP BY c.id ORDER BY c.effective_from DESC,c.id DESC`;
taxRouter.get('/',...requirePermission('tax_configuration','view'),async(_req,res,next)=>{try{res.json({configurations:(await pool.query(configurationQuery)).rows});}catch(e){next(e);}});
taxRouter.post('/',...requirePermission('tax_configuration','create'),saveTax); taxRouter.put('/:id',...requirePermission('tax_configuration','update'),saveTax);
async function saveTax(req,res,next){const client=await pool.connect();try{const body=req.body||{},brackets=Array.isArray(body.brackets)?body.brackets:[];if(!String(body.name||'').trim()||!body.effectiveFrom||!frequencies.has(body.payFrequency)||!brackets.length)return res.status(400).json({error:'Complete the tax configuration and add at least one bracket.'});const normalized=brackets.map(b=>({lower:Number(b.lowerBound),upper:b.upperBound===''||b.upperBound==null?null:Number(b.upperBound),base:Number(b.baseTax),rate:Number(b.ratePercent)})).sort((a,b)=>a.lower-b.lower);if(normalized.some((b,i)=>!Number.isFinite(b.lower)||b.lower<0||(b.upper!==null&&(!Number.isFinite(b.upper)||b.upper<=b.lower))||!Number.isFinite(b.base)||b.base<0||!Number.isFinite(b.rate)||b.rate<0||b.rate>100||(i&&normalized[i-1].upper!==b.lower)))return res.status(400).json({error:'Tax brackets must be valid, continuous, and non-overlapping.'});await client.query('BEGIN');if(body.isActive!==false){const overlap=await client.query(`SELECT id FROM tax_configurations WHERE pay_frequency=$1 AND is_active=TRUE AND id<>COALESCE($4::bigint,0) AND effective_from<=COALESCE($3::date,'infinity'::date) AND COALESCE(effective_to,'infinity'::date)>=$2::date LIMIT 1`,[body.payFrequency,body.effectiveFrom,body.effectiveTo||null,req.params.id||null]);if(overlap.rowCount){await client.query('ROLLBACK');return res.status(409).json({error:'Another active configuration overlaps this frequency and date range.'});}}let saved;if(req.params.id)saved=await client.query(`UPDATE tax_configurations SET name=$1,effective_from=$2,effective_to=$3,pay_frequency=$4,exemption_amount=0,is_active=$5,updated_by=$6,updated_at=NOW() WHERE id=$7 RETURNING id`,[String(body.name).trim(),body.effectiveFrom,body.effectiveTo||null,body.payFrequency,body.isActive!==false,req.user.id,req.params.id]);else saved=await client.query(`INSERT INTO tax_configurations(name,effective_from,effective_to,pay_frequency,exemption_amount,is_active,updated_by) VALUES($1,$2,$3,$4,0,$5,$6) RETURNING id`,[String(body.name).trim(),body.effectiveFrom,body.effectiveTo||null,body.payFrequency,body.isActive!==false,req.user.id]);if(!saved.rowCount){await client.query('ROLLBACK');return res.status(404).json({error:'Tax configuration not found.'});}const id=saved.rows[0].id;await client.query('DELETE FROM tax_brackets WHERE configuration_id=$1',[id]);for(const b of normalized)await client.query('INSERT INTO tax_brackets(configuration_id,lower_bound,upper_bound,base_tax,rate_percent) VALUES($1,$2,$3,$4,$5)',[id,b.lower,b.upper,b.base,b.rate]);await client.query('COMMIT');res.json({id,message:'Tax configuration saved.'});}catch(e){await client.query('ROLLBACK');next(e);}finally{client.release();}}
taxRouter.post('/preview',...requirePermission('tax_configuration','view'),(req,res)=>res.json(calculatePhilippineWithholding({...req.body,brackets:req.body?.brackets||[]})));
